//! Shared domain types for StellarTrace.
//!
//! These types form the contract between ingestion, the rules engine,
//! scoring, alert management, the AI advisor, and the API layer. Keeping
//! them in one crate means every layer agrees on shape without depending
//! on each other's internals.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

/// A Stellar asset, native (XLM) or an issued credit asset.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Asset {
    Native,
    Credit { code: String, issuer: String },
}

impl std::fmt::Display for Asset {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Asset::Native => write!(f, "XLM"),
            Asset::Credit { code, issuer } => write!(f, "{code}:{issuer}"),
        }
    }
}

/// A normalized representation of a Stellar transaction (or a single
/// payment-relevant operation within one), independent of whether it came
/// from Horizon, an RPC event stream, or a Soroban contract invocation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormalizedTransaction {
    /// Stellar transaction hash (hex).
    pub tx_hash: String,
    /// Ledger sequence the transaction was included in.
    pub ledger_sequence: u32,
    pub source_account: String,
    /// Destination account, when the transaction represents a transfer.
    pub destination_account: Option<String>,
    pub asset: Asset,
    /// Amount in the asset's smallest reporting unit as a decimal string
    /// (kept as string to avoid float precision issues with 7-decimal
    /// Stellar amounts).
    pub amount: String,
    pub timestamp: DateTime<Utc>,
    /// True if this transaction invoked a Soroban contract rather than
    /// (or in addition to) a classic payment operation.
    pub is_soroban_invocation: bool,
    pub contract_id: Option<String>,
    /// Free-form metadata for rules that need extra context
    /// (e.g. operation type, memo presence) without widening this struct.
    pub metadata: HashMap<String, String>,
}

impl NormalizedTransaction {
    pub fn amount_f64(&self) -> f64 {
        self.amount.parse().unwrap_or(0.0)
    }
}

/// Severity assigned to a triggered rule or an aggregated alert.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

/// The structured, explainable output of a single rule evaluation.
/// Every field exists so an investigator (or the AI advisor) can see
/// exactly why a rule fired without re-deriving it from raw data.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TriggeredRule {
    pub rule_id: String,
    pub rule_name: String,
    pub severity: Severity,
    /// Human-readable, deterministic explanation of why this fired.
    pub reason: String,
    /// Machine-readable evidence backing `reason` (e.g. thresholds and
    /// observed values) so the explanation can be audited or re-verified.
    pub evidence: HashMap<String, String>,
}

/// Lifecycle status of an alert. Only a human investigator can move an
/// alert into a terminal state; the AI advisor never writes this field.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InvestigationStatus {
    Open,
    UnderInvestigation,
    Escalated,
    Dismissed,
    ConfirmedSuspicious,
}

impl InvestigationStatus {
    pub fn is_terminal(&self) -> bool {
        matches!(self, InvestigationStatus::Dismissed | InvestigationStatus::ConfirmedSuspicious)
    }
}

/// An anomaly/alert record produced by the detection pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub alert_id: Uuid,
    pub tx_hash: String,
    pub source_account: String,
    pub destination_account: Option<String>,
    pub asset: Asset,
    pub amount: String,
    pub timestamp: DateTime<Utc>,
    pub triggered_rules: Vec<TriggeredRule>,
    pub anomaly_score: f64,
    pub severity: Severity,
    pub status: InvestigationStatus,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// The label every AI-generated field must carry. This is never optional:
/// any code path that renders AI output must render this alongside it.
pub const AI_ADVISORY_LABEL: &str =
    "ADVISORY ONLY — generated by AI, not a decision. A human investigator must decide.";

/// Structured, advisory-only output from the AI investigation layer.
/// This type intentionally has no field capable of changing alert state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiRecommendation {
    pub alert_id: Uuid,
    pub label: String,
    pub summary: String,
    pub suspicious_signals: Vec<String>,
    pub relevant_history_context: String,
    pub risk_assessment: String,
    pub recommended_next_steps: Vec<String>,
    pub confidence: f64,
    pub explanation: String,
    pub generated_at: DateTime<Utc>,
    /// True if a real model call succeeded; false if this is a fallback
    /// produced because the AI service was unavailable.
    pub model_available: bool,
}

/// A decision submitted by an authorized human investigator. This is the
/// only thing that can change `Alert::status`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvestigatorDecision {
    pub alert_id: Uuid,
    pub investigator_id: String,
    pub decision: InvestigationStatus,
    pub notes: String,
    pub decided_at: DateTime<Utc>,
}

/// Roles for authorization. Only `Investigator` and `Admin` may submit
/// decisions or change alert status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    Viewer,
    Investigator,
    Admin,
}

impl Role {
    pub fn can_decide(&self) -> bool {
        matches!(self, Role::Investigator | Role::Admin)
    }
}
